# Production
FROM node:lts-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Server
FROM nginx:alpine

WORKDIR /app

COPY docker/nginx/conf/nginx.conf /etc/nginx/conf.d/default.conf

# Копируем только билд
COPY --from=build /app/build ./

EXPOSE 8081

CMD ["nginx", "-g", "daemon off;"]
